(load "ex1.21.scm")

(define (next-odd n)
  (if (even? n)
      (+ n 1)
      (+ n 2)))

(define (prime? n)
  (= (smallest-devisor n) n))

(define (search-for-primes n)
  (define (report-time elapsed-time)
    (newline)
    (display "time: ")
    (display elapsed-time))
  (define (time-prime-test n count start-time)
    (define (start-prime-test n)
      (if (prime? n)
          (report-prime n)
          (start-prime-test (next-odd n))))
    (define (report-prime n)
      (newline)
      (display n)
      (time-prime-test (next-odd n) (- count 1) start-time))
    (if (= 0 count)
        (report-time (- (real-time-clock) start-time))
        (start-prime-test n)))
  (time-prime-test n 3 (real-time-clock)))
