(load "huffman-code-tree.scm")

(define (encode message tree)
  (if (null? message)
      '()
      (append (encode-symbol (car message) tree)
              (encode (cdr message) tree))))

(define (encode-symbol x tree)
  (define (in-set? x set)
    (and (not (null? set))
         (or (eq? x (car set))
             (in-set? x (cdr set)))))
  (define (symbol-in-tree? x tree)
    (in-set? x (symbols tree)))
  (cond ((leaf? tree) '())
        ((symbol-in-tree? x (left-branch tree))
         (cons 0 (encode-symbol x (left-branch tree))))
        ((symbol-in-tree? x (right-branch tree))
         (cons 1 (encode-symbol x (right-branch tree))))
        (else (error "symbol not in tree -- ENCODE-SYMBOL"))))
