(define (equal? item x)
  (or (and (null? item)
           (null? x))
      (and (pair? item)
           (pair? x)
           (equal? (car item) (car x))
           (equal? (cdr item) (cdr x)))
      (and (not (pair? item))
           (not (pair? x))
           (eq? item x))))
