(define (loop? x)
  (define (iter x y)
    (and (not (null? y))
         (pair? y)
         (not (null? (cdr y)))
         (pair? (cdr y))
         (or (eq? x y)
             (iter (cdr x) (cdr (cdr y))))))
  (and (not (null? x))
       (pair? x)
       (iter x (cdr x))))
