(define (loop? x)
  (define (in-set? x set)
    (and (not (null? set))
         (or (eq? x (car set))
             (in-set? x (cdr set)))))
  (define (iter? x set)
    (and (pair? x)
         (not (null? x))
         (or (in-set? x set)
             (iter? (cdr x) (cons x set)))))
  (iter? x '()))
