(define (count-pairs x)
  (define (in-set? x set)
    (and (not (null? set))
         (or (eq? x (car set))
             (in-set? x (cdr set)))))
  (define (iter x set)
    (if (and (pair? x)
             (not (in-set? x set)))
        (iter (car x)
              (iter (cdr x)
                    (cons x set)))
        set))
  (length (iter x '())))
